apiVersion: apps/v1
kind: Deployment
metadata:
  name: fairshare-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fairshare-frontend
  template:
    metadata:
      labels:
        app: fairshare-frontend
    spec:
      containers:
      - name: fairshare-frontend
        image: niharpanchal/fairshare-frontend:latest
        ports:
        - containerPort: 80
        
---
 
apiVersion: v1
kind: Service
metadata:
  name: fairshare-service
spec:
  selector:
    app: fairshare-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
